
# Simple N-BEATS

epochs: 100
eval_every: 5

model:
  num_stacks: 1
  blocks_per_stack: 5  
  fc_dim: 256
  horizon: 7
  lookback_horizon_ratio: 3
  forecast_horizon_ratio: 2

optim:
  name: sgd
  lr: 0.00001
  weight_decay: 0.0001

scheduler:
  name: 

dataloader:
  ticker: AMZN
  batch_size: 64
  horizon: 7
  forecast_horizon_ratio: 2
  lookback_horizon_ratio: 3